services:
  influxdb:
    image: influxdb:2.7
    container_name: weather_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-weather123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-weather-station}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-weather-data}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-weather-station-token-12345}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - weather-network

  grafana:
    image: grafana/grafana:latest
    container_name: weather_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-grafana123}
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY:-change-this-secret-key}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - weather-network
    depends_on:
      - influxdb

  redis:
    image: redis:7-alpine
    container_name: weather_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data
    networks:
      - weather-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: weather_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    networks:
      - weather-network

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
  redis-data:

networks:
  weather-network:
    driver: bridge